name: Test the dsb
on:
  schedule:
    - cron: "20 0 * * *"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: yarn
      - run: yarn build
      - run: yarn test
        env:
          DSBUSERNAME: ${{ secrets.DSBUSERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
